model = "gpt-5.4"
model_reasoning_effort = "medium"
[plugins."github@openai-curated"]
enabled = true

[projects."/home/arnab/code/collegeCode/sem6/applications/Project-Initial"]
trust_level = "trusted"

[projects."/home/arnab/code/personalCode/AutoLinks"]
trust_level = "trusted"

[projects."/home/arnab/code/personalCode/clinic-appointment-booking-engine"]
trust_level = "trusted"

[projects."/home/arnab/code/personalCode/flipkart-hack"]
trust_level = "trusted"

[projects."/home/arnab/code/personalCode/speculators"]
trust_level = "trusted"
