# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(161316)
$foreground = rgb(F4DCDA)
$color0 = rgb(3D3B3E)
$color1 = rgb(150C16)
$color2 = rgb(150C16)
$color3 = rgb(522B2B)
$color4 = rgb(824477)
$color5 = rgb(6C6990)
$color6 = rgb(A7756F)
$color7 = rgb(E7C5C1)
$color8 = rgb(A18A87)
$color9 = rgb(1C101E)
$color10 = rgb(1C101E)
$color11 = rgb(6D3939)
$color12 = rgb(AE5B9E)
$color13 = rgb(908CC0)
$color14 = rgb(DF9C94)
$color15 = rgb(E7C5C1)
