# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4DCDA
background         #161316
cursor             #88767C

active_tab_foreground     #161316
active_tab_background     #F4DCDA
inactive_tab_foreground   #F4DCDA
inactive_tab_background   #161316

active_border_color   #F4DCDA
inactive_border_color #161316
bell_border_color     #150C16

color0      #3D3B3E
color1		#150C16
color2		#150C16
color3		#522B2B
color4		#824477
color5		#6C6990
color6		#A7756F
color7		#E7C5C1
color8		#A18A87
color9		#1C101E
color10		#1C101E
color11		#6D3939
color12		#AE5B9E
color13		#908CC0
color14		#DF9C94
color15		#E7C5C1
